### ISSUE TITLE
[Crash]: Incompatibility with Origins Forge

### ISSUE THREAD

**Issue by muon-rw** [Fuzss/visualworkbench#42]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

VisualWorkbench-v8.0.0-1.20.1-Forge

### Notes (Required)

Versions:
origins-forge-1.20.1-1.10.0.2-all
VisualWorkbench-v8.0.0-1.20.1-Forge

Steps to reproduce:
Open a crafting table GUI, try to place an item in the crafting grid.
Crashes the server (in this log Neruina catches it and kills the player)

Potentially the same issue as #40 ?

Full log: https://mclo.gs/za1qyW8

Issue reproduced on line 7932:
```--
7933 | net.minecraft.ReportedException: Container click
7934 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:308) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7935 | at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1550) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7936 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7937 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7938 | at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7939 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7940 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7941 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7942 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7943 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7944 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7945 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7946 | at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7947 | at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7948 | at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7949 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7950 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7951 | at java.lang.Thread.run(Thread.java:1583) ~[?:?]
7952 | Caused by: java.lang.ClassCastException: class fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer cannot be cast to class io.github.apace100.apoli.access.PowerCraftingInventory (fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer is in module visualworkbench@8.0.0 of loader 'TRANSFORMER' @3dbbed3e; io.github.apace100.apoli.access.PowerCraftingInventory is in module apoli@1.20.1-2.9.0.2 of loader 'TRANSFORMER' @3dbbed3e)
7953 | at net.minecraft.world.inventory.CraftingMenu.handler$zea000$clearPowerCraftingInventory(CraftingMenu.java:537) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7954 | at net.minecraft.world.inventory.CraftingMenu.m_150546_(CraftingMenu.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7955 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotsChanged$3(ModCraftingMenu.java:66) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7956 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7957 | at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7958 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7959 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_6199_(ModCraftingMenu.java:65) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7960 | at fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer.m_6836_(ForwardingCraftingContainer.java:58) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7961 | at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7962 | at net.minecraft.world.inventory.Slot.m_269060_(Slot.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7963 | at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:165) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7964 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7965 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:340) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7966 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7967 | ... 17 more
7968 | [23:27:10] [Server thread/WARN]: Server: §b[Neruina]: §cCaught Ticking Entity [mura_ven] at position [x=-179.0, y=66.0, z=-54.0]. It has been killed.
7969 | java.lang.ClassCastException: class fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer cannot be cast to class io.github.apace100.apoli.access.PowerCraftingInventory (fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer is in module visualworkbench@8.0.0 of loader 'TRANSFORMER' @3dbbed3e; io.github.apace100.apoli.access.PowerCraftingInventory is in module apoli@1.20.1-2.9.0.2 of loader 'TRANSFORMER' @3dbbed3e)
7970 | at net.minecraft.world.inventory.CraftingMenu.handler$zea000$clearPowerCraftingInventory(CraftingMenu.java:537) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7971 | at net.minecraft.world.inventory.CraftingMenu.m_150546_(CraftingMenu.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7972 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotsChanged$3(ModCraftingMenu.java:66) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7973 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7974 | at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7975 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7976 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_6199_(ModCraftingMenu.java:65) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7977 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotChanged$4(ModCraftingMenu.java:76) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7978 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7979 | at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7980 | at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7981 | at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_7934_(ModCraftingMenu.java:74) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
7982 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenu.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7983 | at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:171) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7984 | at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7985 | at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7986 | at net.minecraft.world.level.Level.mixinextras$bridge$accept$160(Level.java) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7987 | at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:112) ~[neruina-1.2.2-forge+1.18.2-1.20.1.jar%23613!/:?]
7988 | at net.minecraft.world.level.Level.wrapOperation$cgj000$catchTickingEntities(Level.java:3040) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7989 | at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7990 | at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7991 | at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7992 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7993 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7994 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7995 | at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7996 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7997 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
7998 | at java.lang.Thread.run(Thread.java:1583) ~[?:?]
7999 | [23:27:10] [Render thread/INFO]: [CHAT] §b[Neruina]: §cCaught Ticking Entity [mura_ven] at position [x=-179.0, y=66.0, z=-54.0]. It has been killed.

[23:27:10] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@5688affd, suppressing error
net.minecraft.ReportedException: Container click
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:308) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1550) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer cannot be cast to class io.github.apace100.apoli.access.PowerCraftingInventory (fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer is in module visualworkbench@8.0.0 of loader 'TRANSFORMER' @3dbbed3e; io.github.apace100.apoli.access.PowerCraftingInventory is in module apoli@1.20.1-2.9.0.2 of loader 'TRANSFORMER' @3dbbed3e)
	at net.minecraft.world.inventory.CraftingMenu.handler$zea000$clearPowerCraftingInventory(CraftingMenu.java:537) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.CraftingMenu.m_150546_(CraftingMenu.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotsChanged$3(ModCraftingMenu.java:66) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_6199_(ModCraftingMenu.java:65) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer.m_6836_(ForwardingCraftingContainer.java:58) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.Slot.m_269060_(Slot.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:165) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:340) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	... 17 more
[23:27:10] [Server thread/WARN]: Server: §b[Neruina]: §cCaught Ticking Entity [mura_ven] at position [x=-179.0, y=66.0, z=-54.0]. It has been killed.
java.lang.ClassCastException: class fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer cannot be cast to class io.github.apace100.apoli.access.PowerCraftingInventory (fuzs.visualworkbench.world.inventory.ForwardingCraftingContainer is in module visualworkbench@8.0.0 of loader 'TRANSFORMER' @3dbbed3e; io.github.apace100.apoli.access.PowerCraftingInventory is in module apoli@1.20.1-2.9.0.2 of loader 'TRANSFORMER' @3dbbed3e)
	at net.minecraft.world.inventory.CraftingMenu.handler$zea000$clearPowerCraftingInventory(CraftingMenu.java:537) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.CraftingMenu.m_150546_(CraftingMenu.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotsChanged$3(ModCraftingMenu.java:66) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_6199_(ModCraftingMenu.java:65) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.lambda$slotChanged$4(ModCraftingMenu.java:76) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39294_(ContainerLevelAccess.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.ContainerLevelAccess.m_39292_(ContainerLevelAccess.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at fuzs.visualworkbench.world.inventory.ModCraftingMenu.m_[7934](https://mclo.gs/za1qyW8#L7934)_(ModCraftingMenu.java:74) ~[VisualWorkbench-v8.0.0-1.20.1-Forge.jar%23704!/:8.0.0]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenu.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:171) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.level.Level.mixinextras$bridge$accept$160(Level.java) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:112) ~[neruina-1.2.2-forge+1.18.2-1.20.1.jar%23613!/:?]
	at net.minecraft.world.level.Level.wrapOperation$cgj000$catchTickingEntities(Level.java:3040) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23720!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:27:10] [Render thread/INFO]: [CHAT] §b[Neruina]: §cCaught Ticking Entity [mura_ven] at position [x=-179.0, y=66.0, z=-54.0]. It has been killed.``````

### Crash Report (Required)

https://mclo.gs/za1qyW8

### latest.log (Optional)

_No response_

**Comment by muon-rw** [comment]
Origins Forge apparently plans to fix this on their end:

https://github.com/EdwinMindcraft/origins-architectury/issues/374#issuecomment-1751932150

**Comment by muon-rw** [comment]
Fixed in https://github.com/EdwinMindcraft/apoli/commit/1a6a5bff010353fadbc870fe60222d8a9e57af53
