### ISSUE TITLE
[Bug] [1.21] Visual Work Bench is not working.

### ISSUE THREAD

**Issue by Periam** [Fuzss/visualworkbench#65]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1 

### Mod Version(s) (Required)

visualworkbench-v21.0.1-1.21-Neoforge

### Other Mods Involved (Required)

Yes

### Notes (Required)

When playing the game with a homemade modpacck, after creating the Workbench, I can not used to craft, the visual workbench is not opening to place items.

10:30:19.087
game
at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[client-1.21-20240613.152323-srg.jar%23439!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
10:30:19.087
game
at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21-20240613.152323-srg.jar%23439!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
10:30:19.087
game
at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:825) ~[client-1.21-20240613.152323-srg.jar%23439!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
10:30:19.087
game
at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[client-1.21-20240613.152323-srg.jar%23439!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
10:30:19.087
game
at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23439!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
10:30:19.087
game
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

### latest.log (Required)

https://pastebin.com/V3DwzY9n

**Comment by Periam** [comment]
I found that there is an incompatibility with FastworkBench (fastworkbench-1.21-9.1.1) and dependencies
The error was reduced to the both mods installed in the same instance

Attached new logs
https://pastebin.com/h9aXFbQs

**Comment by Fuzss** [comment]
Does this version work for you?

https://cdn.discordapp.com/attachments/917550806922846299/1265274540930633809/VisualWorkbench-v21.0.2.944-1.21-NeoForge.jar?ex=66a0ea3e&is=669f98be&hm=0e846b642497dbdf9c11a424b641b0a21d3b72dec498b312a25b2dcb0631f265&

**Comment by Periam** [comment]
With the version provided now I can access the workbench and built, but I believe there is still an issue since i pick up the tool in this case and the visual version is still there.
![image](https://github.com/user-attachments/assets/96c50190-ee5e-4957-b8f8-e67beb0db977)

**Comment by Zelioth** [comment]
I can also confirm the on version 21.0.1 NeoForge visual work bench changes the crafting tables from the mod they were originally to "Visual Workbench" as the mod its coming from. It also makes crafting tables unable to be accessed and crafted in.

**Comment by Fuzss** [comment]
@Periam The new version is now publicly released. No clue why the visual glitch happens, but at least there is no more crash which is the most important part.

**Comment by Zelioth** [comment]
> @Zelioth This is how the mod works.

I assume you mean the renaming workbenches. That is fine but the not being able to access isn't so much haha.

**Comment by Periam** [comment]
@Fuzss, thanks now the workbench can be accessed and can be used. There is still the issue of the visual glitch but the main part works

**Comment by Zelioth** [comment]
> @Periam The new version is now publicly released. No clue why the visual glitch happens, but at least there is no more crash which is the most important part.

Can you upload the fix to 1.21.1 please? VW works on 1.21.1 just the fix wasn't uploaded to it

**Comment by Zelioth** [comment]
> @Periam The new version is now publicly released. No clue why the visual glitch happens, but at least there is no more crash which is the most important part.

Could you please upload the version to 1.21.1. The mod works on that version for NeoForge but doesn't seem to be listed as a supported mod

**Comment by Zelioth** [comment]
I believe a new issue is now present on 1.21.1. When accessing a workbench with VW activate it pushes you out of the world and says there was a connection lost Network Protocol error 

[disconnect-2024-08-18_00.45.25-client.txt](https://github.com/user-attachments/files/16647310/disconnect-2024-08-18_00.45.25-client.txt)

This was on a single player world
